//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioDevice_Quickswitcher {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class ChosenAudioDevices : global::System.Configuration.ApplicationSettingsBase {
        
        private static ChosenAudioDevices defaultInstance = ((ChosenAudioDevices)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ChosenAudioDevices())));
        
        public static ChosenAudioDevices Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string originalDefaultDeviceId {
            get {
                return ((string)(this["originalDefaultDeviceId"]));
            }
            set {
                this["originalDefaultDeviceId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string alternateDefaultDeviceId {
            get {
                return ((string)(this["alternateDefaultDeviceId"]));
            }
            set {
                this["alternateDefaultDeviceId"] = value;
            }
        }
    }
}
